development:
  driver: postgres
  url: "postgres://gophers@localhost:5432/gophers?sslmode=disable"

test:
  driver: postgres
  url: "postgres://gophers@localhost:5432/gophers_test?sslmode=disable"

circleci:
  driver: postgres
  url: "postgres://ubuntu:@127.0.0.1:5432/circle_test"

production:
  driver: postgres
  url: "postgres://evzgyubseakspv:6zP01ZJ9OmvPzSPoGmonXSquN8@ec2-54-221-225-242.compute-1.amazonaws.com:5432/d2jqlco0k2hl92"
